# Generated by Django 4.2.2 on 2023-10-13 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_alter_comment_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.AddField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
